### ISSUE TITLE
Create main page

### ISSUE THREAD

**Issue by lgainsbrook** [chingu-voyages/v38-geckos-team-04#15]
**__Feature Description__**
Display main page

**__Major User Stories/tasks__**
- create core files and merge to GitHub repo
- create template based on Jacek's sketch
- make the website responsive

**__Additional Considerations__**

![image](https://user-images.githubusercontent.com/25104873/158261035-3825c819-5c12-4edc-89e0-85be4edfa25a.png)

**Comment by uwojeyamudiaga** [comment]
This epic is completed.
